### ISSUE TITLE
bower fail to install dependencies

### ISSUE THREAD

**Issue by seminice** [nokia-wroclaw/hackathon-goidea#1]
I wanted to run this project for educational purpose but when running bower install 
I get this
`bower retry         Download of https://github.com/angular/bower-angular/archive/v1.2.28.tar.gz failed with ETIMEDOUT, retrying in 1.5s
bower retry         Download of https://github.com/arshaw/fullcalendar/archive/v1.6.7.tar.gz failed with ETIMEDOUT, retrying in 1.9s
bower retry         Download of https://github.com/components/jqueryui/archive/1.10.4.tar.gz failed with ETIMEDOUT, retrying in 1.7s`

any ideas?

**Comment by chmurson** [comment]
Quick fix: remove .bowerrc file

Or connect to nokia's intranet via VPN, if you have an access ;)

If you are outside of nokia, and want to commit your changes, then let me
know, we can figure out something.

**Comment by seminice** [comment]
Thank you it worked using your quick fix, I'm outside nokia, but your project is the only angular/beego (full non-Chinese) example I could find on github .. O.o 
Thanks again.
